### ISSUE TITLE
Use remote port when connecting to remote host to fetch random remote port

### ISSUE THREAD

**Issue by kinow** [NERSC/sshspawner#39]
Hi,

It looks like [when the spawner tries to execute the remote script](https://github.com/NERSC/sshspawner/blob/07f690249333101c16fa5511426fff6b0a7dd378/sshspawner/sshspawner.py#L191) that fetches the remote IP + port, it calls [`asyncssh.connect](https://github.com/ronf/asyncssh/blob/776a87d36fadcdd921166b45b3b083edf5a70ef4/asyncssh/connection.py#L5700) without providing the `port` parameter.

This cases `asyncssh.connect` to use the `_DEFAULT_PORT` value, which is 22. I have a Docker container running `sshd` listening to some port like 32768, and when running the spawner I get:

```
[I 2019-05-28 16:53:02.715 JupyterHub log:174] 302 GET /hub/spawn -> /hub/spawn-pending/kinow (kinow@::1) 118.48ms
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/jupyterhub/handlers/base.py:697> exception=ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 22)")>
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 889, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 807, in finish_user_spawn
    await spawn_future
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/jupyterhub/user.py", line 642, in spawn
    raise e
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/jupyterhub/user.py", line 546, in spawn
    url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/sshspawner/sshspawner.py", line 104, in start
    self.remote_ip, port = await self.remote_random_port()
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/sshspawner/sshspawner.py", line 191, in remote_random_port
    async with asyncssh.connect(self.remote_host,username=username,client_keys=[(k,c)],known_hosts=None) as conn:
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/asyncssh/misc.py", line 192, in __aenter__
    self._result = yield from self._coro
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/asyncssh/connection.py", line 5724, in connect
    conn, _ = yield from create_connection(None, host, port, **kwargs)
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/asyncssh/connection.py", line 5332, in create_connection
    local_addr=local_addr)
  File "/home/kinow/anaconda3/lib/python3.7/asyncio/base_events.py", line 959, in create_connection
    raise exceptions[0]
  File "/home/kinow/anaconda3/lib/python3.7/asyncio/base_events.py", line 946, in create_connection
    await self.sock_connect(sock, address)
  File "/home/kinow/anaconda3/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/home/kinow/anaconda3/lib/python3.7/asyncio/selector_events.py", line 494, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 22)
```

**Comment by rcthomas** [comment]
This will be addressed during the cleanup in progress.  I just added it to the clean-up branch.  The `remote_port` name was confusing so I've decided to move it to `ssh_port` to be clear what it is for (not something like the port for the server on the remote side).
