### ISSUE TITLE
Should we be setting self.port somewhere?

### ISSUE THREAD

**Issue by rcthomas** [NERSC/sshspawner#6]
Under wrapspawner/profilespawner with cori19 config, I am getting a failure to spawn like this:

```jupytertest_1  | [E 2017-09-23 12:23:23.454 JupyterHub pages:143] Failed to spawn single-user server with form
jupytertest_1  |     Traceback (most recent call last):
jupytertest_1  |       File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/pages.py", line 141, in post
jupytertest_1  |         yield self.spawn_single_user(user, options=options)
jupytertest_1  |       File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 474, in spawn_single_user
jupytertest_1  |         yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
jupytertest_1  |       File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 444, in finish_user_spawn
jupytertest_1  |         yield spawn_future
jupytertest_1  |       File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 437, in spawn
jupytertest_1  |         raise e
jupytertest_1  |       File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 378, in spawn
jupytertest_1  |         ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
jupytertest_1  |       File "/opt/anaconda3/lib/python3.6/types.py", line 248, in wrapped
jupytertest_1  |         coro = func(*args, **kwargs)
jupytertest_1  |       File "/opt/anaconda3/lib/python3.6/site-packages/sshspawner/sshspawner.py", line 254, in start
jupytertest_1  |         cmd.extend(self.get_args())
jupytertest_1  |       File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/spawner.py", line 628, in get_args
jupytertest_1  |         elif self.server.port:
jupytertest_1  |     AttributeError: 'NoneType' object has no attribute 'port'```

**Comment by rcthomas** [comment]
The exact line that complains in spawner is deprecated; if we set `self.port` it wouldn't get there.  Not 100% sure why this works outside `ProfilesSpawner` yet.

**Comment by rcthomas** [comment]
Yeah look at https://github.com/jupyterhub/jupyterhub/blob/6bbfcdfe4f616c804cfccdddcb3b9bd7f927e3c9/jupyterhub/spawner.py#L966 where the `start` method sets this.  Perhaps it wasn't being used before.  We may just need to rename the random port attribute.
